### ISSUE TITLE
Pull access denied for dicom-rst

### ISSUE THREAD

**Issue by Jolly5** [UMEssen/DICOM-RST#13]
In the [Installation Guide](https://umessen.github.io/DICOM-RST/installing.html#using-docker), the following command is provided to start the docker container:
```bash
docker run -p 8080:8080 -p 7001:7001 dicom-rst
```

However, this results in the following error:
```
Unable to find image 'dicom-rst:latest' locally
docker: Error response from daemon: pull access denied for dicom-rst, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

Apparently, docker does not recognize the image `dicom-rst`. Supplying the full name works:
```bash
docker run -p 8080:8080 -p 7001:7001 ghcr.io/umessen/dicom-rst:latest
```

I suggest the documentation be updated to get around this issue or someone tell me that I'm unable to use docker correctly. :)

**Comment by nickamzol** [comment]
Thank you for reporting this issue!
The documentation did not use the fully qualified image name.

Fixed in https://github.com/UMEssen/DICOM-RST/commit/6ca6c6e54b98af28adc7174f4c88c169bbe22e0c
