### ISSUE TITLE
Documentation of Routes with Examples

### ISSUE THREAD

**Issue by MaxOremek** [UMEssen/DICOM-RST#3]
It would be nice to add examples to the routes such that the user could qucikly see how data retrieval works

eg. for retrieval of studies where xxx is the pacs server name
```
localhost:8080/aets/xxxx/studies
```

**Comment by nickamzol** [comment]
Take a look at our new documentation website:
https://umessen.github.io/DICOM-RST/usage-guide.html

It lists all available endpoints (for both DICOMweb and DICOM-RST APIs) and provides an OpenAPI [specification file](https://umessen.github.io/DICOM-RST/resources/openapi.yaml).

Feel free to reopen this issue if you have any follow-up questions.
